import { render, toPlainText } from 'react-email';
import VerifyEmail from '../src/templates/verify-email';

/*
 * Renders every email once, at build time, into src/rendered/*.ts. The running
 * server then needs neither React nor React Email: it substitutes the two
 * placeholders below and sends. Re-run with `bun run email:render` after editing
 * a template; CI fails if the committed output is stale.
 */
export const PLACEHOLDERS = {
    verificationUrl: '{{verificationUrl}}',
    logoUrl: '{{logoUrl}}',
} as const;

const purposes = ['register', 'recover'] as const;
const rendered: Record<string, { html: string; text: string }> = {};
for (const purpose of purposes) {
    const html = await render(
        <VerifyEmail
            purpose={purpose}
            verificationUrl={PLACEHOLDERS.verificationUrl}
            logoUrl={PLACEHOLDERS.logoUrl}
        />,
    );
    for (const token of Object.values(PLACEHOLDERS))
        if (!html.includes(token)) throw new Error(`Rendered ${purpose} email lacks ${token}.`);
    rendered[purpose] = { html, text: toPlainText(html) };
}

const source = `/* Generated by \`bun run email:render\` from src/templates/verify-email.tsx. Do not edit. */
export const verifyEmail = ${JSON.stringify(rendered, null, 4)} as const;
`;
await Bun.write(new URL('../src/rendered/verify-email.ts', import.meta.url), source);
console.info(`Rendered ${purposes.length} verification emails.`);
