import { render, toPlainText } from 'react-email';
import ShareNotice from '../src/templates/share-notice';
import VerifyEmail from '../src/templates/verify-email';

/*
 * Renders every email once, at build time, into src/rendered/*.ts. The running
 * server then needs neither React nor React Email: it substitutes the two
 * placeholders below and sends. Re-run with `bun run email:render` after editing
 * a template; CI fails if the committed output is stale.
 */
export const PLACEHOLDERS = {
    verificationUrl: '{{verificationUrl}}',
    logoUrl: '{{logoUrl}}',
} as const;

const purposes = ['register', 'recover'] as const;
const rendered: Record<string, { html: string; text: string }> = {};
for (const purpose of purposes) {
    const html = await render(
        <VerifyEmail
            purpose={purpose}
            verificationUrl={PLACEHOLDERS.verificationUrl}
            logoUrl={PLACEHOLDERS.logoUrl}
        />,
    );
    for (const token of Object.values(PLACEHOLDERS))
        if (!html.includes(token)) throw new Error(`Rendered ${purpose} email lacks ${token}.`);
    rendered[purpose] = { html, text: toPlainText(html) };
}

const source = `/* Generated by \`bun run email:render\` from src/templates/verify-email.tsx. Do not edit. */
export const verifyEmail = ${JSON.stringify(rendered, null, 4)} as const;
`;
await Bun.write(new URL('../src/rendered/verify-email.ts', import.meta.url), source);
console.info(`Rendered ${purposes.length} verification emails.`);

/* The share notice: one template, four placeholders the server fills. */
export const SHARE_PLACEHOLDERS = {
    granterName: '{{granterName}}',
    granterEmail: '{{granterEmail}}',
    sharedUrl: '{{sharedUrl}}',
    logoUrl: '{{logoUrl}}',
} as const;
const shareRendered: Record<string, { html: string; text: string }> = {};
for (const role of ['viewer', 'editor'] as const) {
    const html = await render(
        <ShareNotice
            role={role}
            granterName={SHARE_PLACEHOLDERS.granterName}
            granterEmail={SHARE_PLACEHOLDERS.granterEmail}
            sharedUrl={SHARE_PLACEHOLDERS.sharedUrl}
            logoUrl={SHARE_PLACEHOLDERS.logoUrl}
        />,
    );
    for (const token of Object.values(SHARE_PLACEHOLDERS))
        if (!html.includes(token)) throw new Error(`Rendered share email lacks ${token}.`);
    shareRendered[role] = { html, text: toPlainText(html) };
}
await Bun.write(
    new URL('../src/rendered/share-notice.ts', import.meta.url),
    `/* Generated by \`bun run email:render\` from src/templates/share-notice.tsx. Do not edit. */
export const shareNotice = ${JSON.stringify(shareRendered, null, 4)} as const;
`,
);
console.info('Rendered 2 share notices.');
