/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AccountDeletedRouteRouteImport } from './routes/account-deleted/route'
import { Route as DesignDotmdRouteImport } from './routes/design[.]md'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as OgDotjpgRouteImport } from './routes/og[.]jpg'
import { Route as PrivacyRouteRouteImport } from './routes/privacy/route'
import { Route as RecoverRouteRouteImport } from './routes/recover/route'
import { Route as RegisterRouteRouteImport } from './routes/register/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SecurityRouteRouteImport } from './routes/security/route'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteRouteImport } from './routes/terms/route'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as RecoverIndexRouteImport } from './routes/recover/index'
import { Route as RecoverCheckEmailRouteImport } from './routes/recover/check-email'
import { Route as RecoverCompleteRouteImport } from './routes/recover/complete'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as RegisterCheckEmailRouteImport } from './routes/register/check-email'
import { Route as RegisterCompleteRouteImport } from './routes/register/complete'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/app/account'
import { Route as AuthenticatedAppRecoveryKeyRouteImport } from './routes/_authenticated/app/recovery-key'
import { Route as AuthenticatedSetupRecoveryKeyRouteImport } from './routes/_authenticated/setup/recovery-key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletedRouteRoute = AccountDeletedRouteRouteImport.update({
  id: '/account-deleted',
  path: '/account-deleted',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignDotmdRoute = DesignDotmdRouteImport.update({
  id: '/design.md',
  path: '/design.md',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDotjpgRoute = OgDotjpgRouteImport.update({
  id: '/og.jpg',
  path: '/og.jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRouteRoute = PrivacyRouteRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRouteRoute = RecoverRouteRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRouteRoute = RegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRouteRoute = SecurityRouteRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRouteRoute = TermsRouteRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverIndexRoute = RecoverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecoverRouteRoute,
} as any)
const RecoverCheckEmailRoute = RecoverCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => RecoverRouteRoute,
} as any)
const RecoverCompleteRoute = RecoverCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => RecoverRouteRoute,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const RegisterCheckEmailRoute = RegisterCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const RegisterCompleteRoute = RegisterCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppRecoveryKeyRoute =
  AuthenticatedAppRecoveryKeyRouteImport.update({
    id: '/recovery-key',
    path: '/recovery-key',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedSetupRecoveryKeyRoute =
  AuthenticatedSetupRecoveryKeyRouteImport.update({
    id: '/setup/recovery-key',
    path: '/setup/recovery-key',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-deleted': typeof AccountDeletedRouteRoute
  '/login': typeof LoginRouteRoute
  '/privacy': typeof PrivacyRouteRoute
  '/recover': typeof RecoverRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/security': typeof SecurityRouteRoute
  '/terms': typeof TermsRouteRoute
  '/design.md': typeof DesignDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og.jpg': typeof OgDotjpgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/recover/check-email': typeof RecoverCheckEmailRoute
  '/recover/complete': typeof RecoverCompleteRoute
  '/register/check-email': typeof RegisterCheckEmailRoute
  '/register/complete': typeof RegisterCompleteRoute
  '/blog/': typeof BlogIndexRoute
  '/recover/': typeof RecoverIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/recovery-key': typeof AuthenticatedAppRecoveryKeyRoute
  '/setup/recovery-key': typeof AuthenticatedSetupRecoveryKeyRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deleted': typeof AccountDeletedRouteRoute
  '/login': typeof LoginRouteRoute
  '/privacy': typeof PrivacyRouteRoute
  '/security': typeof SecurityRouteRoute
  '/terms': typeof TermsRouteRoute
  '/design.md': typeof DesignDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og.jpg': typeof OgDotjpgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/recover/check-email': typeof RecoverCheckEmailRoute
  '/recover/complete': typeof RecoverCompleteRoute
  '/register/check-email': typeof RegisterCheckEmailRoute
  '/register/complete': typeof RegisterCompleteRoute
  '/blog': typeof BlogIndexRoute
  '/recover': typeof RecoverIndexRoute
  '/register': typeof RegisterIndexRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/recovery-key': typeof AuthenticatedAppRecoveryKeyRoute
  '/setup/recovery-key': typeof AuthenticatedSetupRecoveryKeyRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-deleted': typeof AccountDeletedRouteRoute
  '/login': typeof LoginRouteRoute
  '/privacy': typeof PrivacyRouteRoute
  '/recover': typeof RecoverRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/security': typeof SecurityRouteRoute
  '/terms': typeof TermsRouteRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/design.md': typeof DesignDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og.jpg': typeof OgDotjpgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/recover/check-email': typeof RecoverCheckEmailRoute
  '/recover/complete': typeof RecoverCompleteRoute
  '/register/check-email': typeof RegisterCheckEmailRoute
  '/register/complete': typeof RegisterCompleteRoute
  '/blog/': typeof BlogIndexRoute
  '/recover/': typeof RecoverIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/_authenticated/app/account': typeof AuthenticatedAppAccountRoute
  '/_authenticated/app/recovery-key': typeof AuthenticatedAppRecoveryKeyRoute
  '/_authenticated/setup/recovery-key': typeof AuthenticatedSetupRecoveryKeyRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-deleted'
    | '/login'
    | '/privacy'
    | '/recover'
    | '/register'
    | '/security'
    | '/terms'
    | '/design.md'
    | '/llms.txt'
    | '/og.jpg'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/app'
    | '/api/$'
    | '/blog/$slug'
    | '/recover/check-email'
    | '/recover/complete'
    | '/register/check-email'
    | '/register/complete'
    | '/blog/'
    | '/recover/'
    | '/register/'
    | '/app/account'
    | '/app/recovery-key'
    | '/setup/recovery-key'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deleted'
    | '/login'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/design.md'
    | '/llms.txt'
    | '/og.jpg'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/$'
    | '/blog/$slug'
    | '/recover/check-email'
    | '/recover/complete'
    | '/register/check-email'
    | '/register/complete'
    | '/blog'
    | '/recover'
    | '/register'
    | '/app/account'
    | '/app/recovery-key'
    | '/setup/recovery-key'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/account-deleted'
    | '/login'
    | '/privacy'
    | '/recover'
    | '/register'
    | '/security'
    | '/terms'
    | '/_authenticated'
    | '/design.md'
    | '/llms.txt'
    | '/og.jpg'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/api/$'
    | '/blog/$slug'
    | '/recover/check-email'
    | '/recover/complete'
    | '/register/check-email'
    | '/register/complete'
    | '/blog/'
    | '/recover/'
    | '/register/'
    | '/_authenticated/app/account'
    | '/_authenticated/app/recovery-key'
    | '/_authenticated/setup/recovery-key'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountDeletedRouteRoute: typeof AccountDeletedRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  PrivacyRouteRoute: typeof PrivacyRouteRoute
  RecoverRouteRoute: typeof RecoverRouteRouteWithChildren
  RegisterRouteRoute: typeof RegisterRouteRouteWithChildren
  SecurityRouteRoute: typeof SecurityRouteRoute
  TermsRouteRoute: typeof TermsRouteRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DesignDotmdRoute: typeof DesignDotmdRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OgDotjpgRoute: typeof OgDotjpgRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSplatRoute: typeof ApiSplatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deleted': {
      id: '/account-deleted'
      path: '/account-deleted'
      fullPath: '/account-deleted'
      preLoaderRoute: typeof AccountDeletedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design.md': {
      id: '/design.md'
      path: '/design.md'
      fullPath: '/design.md'
      preLoaderRoute: typeof DesignDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og.jpg': {
      id: '/og.jpg'
      path: '/og.jpg'
      fullPath: '/og.jpg'
      preLoaderRoute: typeof OgDotjpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover/': {
      id: '/recover/'
      path: '/'
      fullPath: '/recover/'
      preLoaderRoute: typeof RecoverIndexRouteImport
      parentRoute: typeof RecoverRouteRoute
    }
    '/recover/check-email': {
      id: '/recover/check-email'
      path: '/check-email'
      fullPath: '/recover/check-email'
      preLoaderRoute: typeof RecoverCheckEmailRouteImport
      parentRoute: typeof RecoverRouteRoute
    }
    '/recover/complete': {
      id: '/recover/complete'
      path: '/complete'
      fullPath: '/recover/complete'
      preLoaderRoute: typeof RecoverCompleteRouteImport
      parentRoute: typeof RecoverRouteRoute
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/register/check-email': {
      id: '/register/check-email'
      path: '/check-email'
      fullPath: '/register/check-email'
      preLoaderRoute: typeof RegisterCheckEmailRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/register/complete': {
      id: '/register/complete'
      path: '/complete'
      fullPath: '/register/complete'
      preLoaderRoute: typeof RegisterCompleteRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/account': {
      id: '/_authenticated/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/recovery-key': {
      id: '/_authenticated/app/recovery-key'
      path: '/recovery-key'
      fullPath: '/app/recovery-key'
      preLoaderRoute: typeof AuthenticatedAppRecoveryKeyRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/setup/recovery-key': {
      id: '/_authenticated/setup/recovery-key'
      path: '/setup/recovery-key'
      fullPath: '/setup/recovery-key'
      preLoaderRoute: typeof AuthenticatedSetupRecoveryKeyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface RecoverRouteRouteChildren {
  RecoverCheckEmailRoute: typeof RecoverCheckEmailRoute
  RecoverCompleteRoute: typeof RecoverCompleteRoute
  RecoverIndexRoute: typeof RecoverIndexRoute
}

const RecoverRouteRouteChildren: RecoverRouteRouteChildren = {
  RecoverCheckEmailRoute: RecoverCheckEmailRoute,
  RecoverCompleteRoute: RecoverCompleteRoute,
  RecoverIndexRoute: RecoverIndexRoute,
}

const RecoverRouteRouteWithChildren = RecoverRouteRoute._addFileChildren(
  RecoverRouteRouteChildren,
)

interface RegisterRouteRouteChildren {
  RegisterCheckEmailRoute: typeof RegisterCheckEmailRoute
  RegisterCompleteRoute: typeof RegisterCompleteRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteRouteChildren: RegisterRouteRouteChildren = {
  RegisterCheckEmailRoute: RegisterCheckEmailRoute,
  RegisterCompleteRoute: RegisterCompleteRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteRouteWithChildren = RegisterRouteRoute._addFileChildren(
  RegisterRouteRouteChildren,
)

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRoute
  AuthenticatedAppRecoveryKeyRoute: typeof AuthenticatedAppRecoveryKeyRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRoute,
  AuthenticatedAppRecoveryKeyRoute: AuthenticatedAppRecoveryKeyRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedSetupRecoveryKeyRoute: typeof AuthenticatedSetupRecoveryKeyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedSetupRecoveryKeyRoute: AuthenticatedSetupRecoveryKeyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountDeletedRouteRoute: AccountDeletedRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  PrivacyRouteRoute: PrivacyRouteRoute,
  RecoverRouteRoute: RecoverRouteRouteWithChildren,
  RegisterRouteRoute: RegisterRouteRouteWithChildren,
  SecurityRouteRoute: SecurityRouteRoute,
  TermsRouteRoute: TermsRouteRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DesignDotmdRoute: DesignDotmdRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OgDotjpgRoute: OgDotjpgRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSplatRoute: ApiSplatRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
