/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountDeletedRouteRouteImport } from './routes/account-deleted/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as DesignDotmdRouteImport } from './routes/design[.]md'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as OgDotjpgRouteImport } from './routes/og[.]jpg'
import { Route as PrivacyRouteRouteImport } from './routes/privacy/route'
import { Route as RecoverRouteRouteImport } from './routes/recover/route'
import { Route as RegisterRouteRouteImport } from './routes/register/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SecurityRouteRouteImport } from './routes/security/route'
import { Route as ShareOgDotjpgRouteImport } from './routes/share-og[.]jpg'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteRouteImport } from './routes/terms/route'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as AppRecoveryKeyRouteImport } from './routes/app/recovery-key'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as RecoverIndexRouteImport } from './routes/recover/index'
import { Route as RecoverCheckEmailRouteImport } from './routes/recover/check-email'
import { Route as RecoverCompleteRouteImport } from './routes/recover/complete'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as RegisterCheckEmailRouteImport } from './routes/register/check-email'
import { Route as RegisterCompleteRouteImport } from './routes/register/complete'
import { Route as SetupRecoveryKeyRouteImport } from './routes/setup/recovery-key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletedRouteRoute = AccountDeletedRouteRouteImport.update({
  id: '/account-deleted',
  path: '/account-deleted',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignDotmdRoute = DesignDotmdRouteImport.update({
  id: '/design.md',
  path: '/design.md',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDotjpgRoute = OgDotjpgRouteImport.update({
  id: '/og.jpg',
  path: '/og.jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRouteRoute = PrivacyRouteRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRouteRoute = RecoverRouteRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRouteRoute = RegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRouteRoute = SecurityRouteRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareOgDotjpgRoute = ShareOgDotjpgRouteImport.update({
  id: '/share-og.jpg',
  path: '/share-og.jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRouteRoute = TermsRouteRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRecoveryKeyRoute = AppRecoveryKeyRouteImport.update({
  id: '/recovery-key',
  path: '/recovery-key',
  getParentRoute: () => AppRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverIndexRoute = RecoverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecoverRouteRoute,
} as any)
const RecoverCheckEmailRoute = RecoverCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => RecoverRouteRoute,
} as any)
const RecoverCompleteRoute = RecoverCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => RecoverRouteRoute,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const RegisterCheckEmailRoute = RegisterCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const RegisterCompleteRoute = RegisterCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const SetupRecoveryKeyRoute = SetupRecoveryKeyRouteImport.update({
  id: '/setup/recovery-key',
  path: '/setup/recovery-key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-deleted': typeof AccountDeletedRouteRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/privacy': typeof PrivacyRouteRoute
  '/recover': typeof RecoverRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/security': typeof SecurityRouteRoute
  '/terms': typeof TermsRouteRoute
  '/design.md': typeof DesignDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og.jpg': typeof OgDotjpgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/share-og.jpg': typeof ShareOgDotjpgRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/app/account': typeof AppAccountRoute
  '/app/recovery-key': typeof AppRecoveryKeyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/recover/check-email': typeof RecoverCheckEmailRoute
  '/recover/complete': typeof RecoverCompleteRoute
  '/register/check-email': typeof RegisterCheckEmailRoute
  '/register/complete': typeof RegisterCompleteRoute
  '/setup/recovery-key': typeof SetupRecoveryKeyRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/recover/': typeof RecoverIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deleted': typeof AccountDeletedRouteRoute
  '/login': typeof LoginRouteRoute
  '/privacy': typeof PrivacyRouteRoute
  '/security': typeof SecurityRouteRoute
  '/terms': typeof TermsRouteRoute
  '/design.md': typeof DesignDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og.jpg': typeof OgDotjpgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/share-og.jpg': typeof ShareOgDotjpgRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/app/account': typeof AppAccountRoute
  '/app/recovery-key': typeof AppRecoveryKeyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/recover/check-email': typeof RecoverCheckEmailRoute
  '/recover/complete': typeof RecoverCompleteRoute
  '/register/check-email': typeof RegisterCheckEmailRoute
  '/register/complete': typeof RegisterCompleteRoute
  '/setup/recovery-key': typeof SetupRecoveryKeyRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/recover': typeof RecoverIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-deleted': typeof AccountDeletedRouteRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/privacy': typeof PrivacyRouteRoute
  '/recover': typeof RecoverRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/security': typeof SecurityRouteRoute
  '/terms': typeof TermsRouteRoute
  '/design.md': typeof DesignDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og.jpg': typeof OgDotjpgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/share-og.jpg': typeof ShareOgDotjpgRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/app/account': typeof AppAccountRoute
  '/app/recovery-key': typeof AppRecoveryKeyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/recover/check-email': typeof RecoverCheckEmailRoute
  '/recover/complete': typeof RecoverCompleteRoute
  '/register/check-email': typeof RegisterCheckEmailRoute
  '/register/complete': typeof RegisterCompleteRoute
  '/setup/recovery-key': typeof SetupRecoveryKeyRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/recover/': typeof RecoverIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-deleted'
    | '/app'
    | '/login'
    | '/privacy'
    | '/recover'
    | '/register'
    | '/security'
    | '/terms'
    | '/design.md'
    | '/llms.txt'
    | '/og.jpg'
    | '/robots.txt'
    | '/share-og.jpg'
    | '/sitemap.xml'
    | '/api/$'
    | '/app/account'
    | '/app/recovery-key'
    | '/blog/$slug'
    | '/recover/check-email'
    | '/recover/complete'
    | '/register/check-email'
    | '/register/complete'
    | '/setup/recovery-key'
    | '/app/'
    | '/blog/'
    | '/recover/'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deleted'
    | '/login'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/design.md'
    | '/llms.txt'
    | '/og.jpg'
    | '/robots.txt'
    | '/share-og.jpg'
    | '/sitemap.xml'
    | '/api/$'
    | '/app/account'
    | '/app/recovery-key'
    | '/blog/$slug'
    | '/recover/check-email'
    | '/recover/complete'
    | '/register/check-email'
    | '/register/complete'
    | '/setup/recovery-key'
    | '/app'
    | '/blog'
    | '/recover'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/account-deleted'
    | '/app'
    | '/login'
    | '/privacy'
    | '/recover'
    | '/register'
    | '/security'
    | '/terms'
    | '/design.md'
    | '/llms.txt'
    | '/og.jpg'
    | '/robots.txt'
    | '/share-og.jpg'
    | '/sitemap.xml'
    | '/api/$'
    | '/app/account'
    | '/app/recovery-key'
    | '/blog/$slug'
    | '/recover/check-email'
    | '/recover/complete'
    | '/register/check-email'
    | '/register/complete'
    | '/setup/recovery-key'
    | '/app/'
    | '/blog/'
    | '/recover/'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountDeletedRouteRoute: typeof AccountDeletedRouteRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
  PrivacyRouteRoute: typeof PrivacyRouteRoute
  RecoverRouteRoute: typeof RecoverRouteRouteWithChildren
  RegisterRouteRoute: typeof RegisterRouteRouteWithChildren
  SecurityRouteRoute: typeof SecurityRouteRoute
  TermsRouteRoute: typeof TermsRouteRoute
  DesignDotmdRoute: typeof DesignDotmdRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OgDotjpgRoute: typeof OgDotjpgRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShareOgDotjpgRoute: typeof ShareOgDotjpgRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSplatRoute: typeof ApiSplatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SetupRecoveryKeyRoute: typeof SetupRecoveryKeyRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deleted': {
      id: '/account-deleted'
      path: '/account-deleted'
      fullPath: '/account-deleted'
      preLoaderRoute: typeof AccountDeletedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design.md': {
      id: '/design.md'
      path: '/design.md'
      fullPath: '/design.md'
      preLoaderRoute: typeof DesignDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og.jpg': {
      id: '/og.jpg'
      path: '/og.jpg'
      fullPath: '/og.jpg'
      preLoaderRoute: typeof OgDotjpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-og.jpg': {
      id: '/share-og.jpg'
      path: '/share-og.jpg'
      fullPath: '/share-og.jpg'
      preLoaderRoute: typeof ShareOgDotjpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/recovery-key': {
      id: '/app/recovery-key'
      path: '/recovery-key'
      fullPath: '/app/recovery-key'
      preLoaderRoute: typeof AppRecoveryKeyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover/': {
      id: '/recover/'
      path: '/'
      fullPath: '/recover/'
      preLoaderRoute: typeof RecoverIndexRouteImport
      parentRoute: typeof RecoverRouteRoute
    }
    '/recover/check-email': {
      id: '/recover/check-email'
      path: '/check-email'
      fullPath: '/recover/check-email'
      preLoaderRoute: typeof RecoverCheckEmailRouteImport
      parentRoute: typeof RecoverRouteRoute
    }
    '/recover/complete': {
      id: '/recover/complete'
      path: '/complete'
      fullPath: '/recover/complete'
      preLoaderRoute: typeof RecoverCompleteRouteImport
      parentRoute: typeof RecoverRouteRoute
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/register/check-email': {
      id: '/register/check-email'
      path: '/check-email'
      fullPath: '/register/check-email'
      preLoaderRoute: typeof RegisterCheckEmailRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/register/complete': {
      id: '/register/complete'
      path: '/complete'
      fullPath: '/register/complete'
      preLoaderRoute: typeof RegisterCompleteRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/setup/recovery-key': {
      id: '/setup/recovery-key'
      path: '/setup/recovery-key'
      fullPath: '/setup/recovery-key'
      preLoaderRoute: typeof SetupRecoveryKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppRecoveryKeyRoute: typeof AppRecoveryKeyRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppRecoveryKeyRoute: AppRecoveryKeyRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface RecoverRouteRouteChildren {
  RecoverCheckEmailRoute: typeof RecoverCheckEmailRoute
  RecoverCompleteRoute: typeof RecoverCompleteRoute
  RecoverIndexRoute: typeof RecoverIndexRoute
}

const RecoverRouteRouteChildren: RecoverRouteRouteChildren = {
  RecoverCheckEmailRoute: RecoverCheckEmailRoute,
  RecoverCompleteRoute: RecoverCompleteRoute,
  RecoverIndexRoute: RecoverIndexRoute,
}

const RecoverRouteRouteWithChildren = RecoverRouteRoute._addFileChildren(
  RecoverRouteRouteChildren,
)

interface RegisterRouteRouteChildren {
  RegisterCheckEmailRoute: typeof RegisterCheckEmailRoute
  RegisterCompleteRoute: typeof RegisterCompleteRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteRouteChildren: RegisterRouteRouteChildren = {
  RegisterCheckEmailRoute: RegisterCheckEmailRoute,
  RegisterCompleteRoute: RegisterCompleteRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteRouteWithChildren = RegisterRouteRoute._addFileChildren(
  RegisterRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountDeletedRouteRoute: AccountDeletedRouteRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
  PrivacyRouteRoute: PrivacyRouteRoute,
  RecoverRouteRoute: RecoverRouteRouteWithChildren,
  RegisterRouteRoute: RegisterRouteRouteWithChildren,
  SecurityRouteRoute: SecurityRouteRoute,
  TermsRouteRoute: TermsRouteRoute,
  DesignDotmdRoute: DesignDotmdRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OgDotjpgRoute: OgDotjpgRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShareOgDotjpgRoute: ShareOgDotjpgRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSplatRoute: ApiSplatRoute,
  BlogSlugRoute: BlogSlugRoute,
  SetupRecoveryKeyRoute: SetupRecoveryKeyRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
