/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteRouteImport } from './routes/about/route'
import { Route as AccountDeletedRouteRouteImport } from './routes/account-deleted/route'
import { Route as DesignDotmdRouteImport } from './routes/design[.]md'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as OgDotjpgRouteImport } from './routes/og[.]jpg'
import { Route as PricingRouteRouteImport } from './routes/pricing/route'
import { Route as PrivacyRouteRouteImport } from './routes/privacy/route'
import { Route as RecoverRouteRouteImport } from './routes/recover/route'
import { Route as RegisterRouteRouteImport } from './routes/register/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SecurityRouteRouteImport } from './routes/security/route'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteRouteImport } from './routes/terms/route'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as GoSlugRouteImport } from './routes/go/$slug'
import { Route as OgKeyRouteImport } from './routes/og/$key'
import { Route as RCodeRouteImport } from './routes/r/$code'
import { Route as RecoverIndexRouteImport } from './routes/recover/index'
import { Route as RecoverCheckEmailRouteImport } from './routes/recover/check-email'
import { Route as RecoverCompleteRouteImport } from './routes/recover/complete'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as RegisterCheckEmailRouteImport } from './routes/register/check-email'
import { Route as RegisterCompleteRouteImport } from './routes/register/complete'
import { Route as STokenRouteImport } from './routes/s/$token'
import { Route as VsSlugRouteImport } from './routes/vs/$slug'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/app/account'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app/billing'
import { Route as AuthenticatedAppContactsRouteImport } from './routes/_authenticated/app/contacts'
import { Route as AuthenticatedAppRecoveryKeyRouteImport } from './routes/_authenticated/app/recovery-key'
import { Route as AuthenticatedAppReferralsRouteImport } from './routes/_authenticated/app/referrals'
import { Route as AuthenticatedAppSharedRouteImport } from './routes/_authenticated/app/shared'
import { Route as AuthenticatedAppTrashRouteImport } from './routes/_authenticated/app/trash'
import { Route as AuthenticatedSetupRecoveryKeyRouteImport } from './routes/_authenticated/setup/recovery-key'
import { Route as AuthenticatedAppAdminIndexRouteImport } from './routes/_authenticated/app/admin/index'
import { Route as AuthenticatedAppAdminAffiliatesRouteImport } from './routes/_authenticated/app/admin/affiliates'
import { Route as AuthenticatedAppFFolderIdRouteImport } from './routes/_authenticated/app/f.$folderId'
import { Route as AuthenticatedAppAdminReportsIndexRouteImport } from './routes/_authenticated/app/admin/reports/index'
import { Route as AuthenticatedAppAdminReportsReportIdRouteImport } from './routes/_authenticated/app/admin/reports/$reportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletedRouteRoute = AccountDeletedRouteRouteImport.update({
  id: '/account-deleted',
  path: '/account-deleted',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignDotmdRoute = DesignDotmdRouteImport.update({
  id: '/design.md',
  path: '/design.md',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDotjpgRoute = OgDotjpgRouteImport.update({
  id: '/og.jpg',
  path: '/og.jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRouteRoute = PricingRouteRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRouteRoute = PrivacyRouteRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRouteRoute = RecoverRouteRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRouteRoute = RegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRouteRoute = SecurityRouteRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRouteRoute = TermsRouteRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GoSlugRoute = GoSlugRouteImport.update({
  id: '/go/$slug',
  path: '/go/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OgKeyRoute = OgKeyRouteImport.update({
  id: '/og/$key',
  path: '/og/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverIndexRoute = RecoverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecoverRouteRoute,
} as any)
const RecoverCheckEmailRoute = RecoverCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => RecoverRouteRoute,
} as any)
const RecoverCompleteRoute = RecoverCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => RecoverRouteRoute,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const RegisterCheckEmailRoute = RegisterCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const RegisterCompleteRoute = RegisterCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VsSlugRoute = VsSlugRouteImport.update({
  id: '/vs/$slug',
  path: '/vs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppContactsRoute =
  AuthenticatedAppContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppRecoveryKeyRoute =
  AuthenticatedAppRecoveryKeyRouteImport.update({
    id: '/recovery-key',
    path: '/recovery-key',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppReferralsRoute =
  AuthenticatedAppReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSharedRoute = AuthenticatedAppSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppTrashRoute = AuthenticatedAppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedSetupRecoveryKeyRoute =
  AuthenticatedSetupRecoveryKeyRouteImport.update({
    id: '/setup/recovery-key',
    path: '/setup/recovery-key',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminIndexRoute =
  AuthenticatedAppAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAdminAffiliatesRoute =
  AuthenticatedAppAdminAffiliatesRouteImport.update({
    id: '/admin/affiliates',
    path: '/admin/affiliates',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFFolderIdRoute =
  AuthenticatedAppFFolderIdRouteImport.update({
    id: '/f/$folderId',
    path: '/f/$folderId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAdminReportsIndexRoute =
  AuthenticatedAppAdminReportsIndexRouteImport.update({
    id: '/admin/reports/',
    path: '/admin/reports/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAdminReportsReportIdRoute =
  AuthenticatedAppAdminReportsReportIdRouteImport.update({
    id: '/admin/reports/$reportId',
    path: '/admin/reports/$reportId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/account-deleted': typeof AccountDeletedRouteRoute
  '/login': typeof LoginRouteRoute
  '/pricing': typeof PricingRouteRoute
  '/privacy': typeof PrivacyRouteRoute
  '/recover': typeof RecoverRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/security': typeof SecurityRouteRoute
  '/terms': typeof TermsRouteRoute
  '/design.md': typeof DesignDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og.jpg': typeof OgDotjpgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/og/$key': typeof OgKeyRoute
  '/r/$code': typeof RCodeRoute
  '/recover/check-email': typeof RecoverCheckEmailRoute
  '/recover/complete': typeof RecoverCompleteRoute
  '/register/check-email': typeof RegisterCheckEmailRoute
  '/register/complete': typeof RegisterCompleteRoute
  '/s/$token': typeof STokenRoute
  '/vs/$slug': typeof VsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/recover/': typeof RecoverIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/contacts': typeof AuthenticatedAppContactsRoute
  '/app/recovery-key': typeof AuthenticatedAppRecoveryKeyRoute
  '/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/app/shared': typeof AuthenticatedAppSharedRoute
  '/app/trash': typeof AuthenticatedAppTrashRoute
  '/setup/recovery-key': typeof AuthenticatedSetupRecoveryKeyRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/affiliates': typeof AuthenticatedAppAdminAffiliatesRoute
  '/app/f/$folderId': typeof AuthenticatedAppFFolderIdRoute
  '/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/app/admin/reports/$reportId': typeof AuthenticatedAppAdminReportsReportIdRoute
  '/app/admin/reports/': typeof AuthenticatedAppAdminReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/account-deleted': typeof AccountDeletedRouteRoute
  '/login': typeof LoginRouteRoute
  '/pricing': typeof PricingRouteRoute
  '/privacy': typeof PrivacyRouteRoute
  '/security': typeof SecurityRouteRoute
  '/terms': typeof TermsRouteRoute
  '/design.md': typeof DesignDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og.jpg': typeof OgDotjpgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/og/$key': typeof OgKeyRoute
  '/r/$code': typeof RCodeRoute
  '/recover/check-email': typeof RecoverCheckEmailRoute
  '/recover/complete': typeof RecoverCompleteRoute
  '/register/check-email': typeof RegisterCheckEmailRoute
  '/register/complete': typeof RegisterCompleteRoute
  '/s/$token': typeof STokenRoute
  '/vs/$slug': typeof VsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/recover': typeof RecoverIndexRoute
  '/register': typeof RegisterIndexRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/contacts': typeof AuthenticatedAppContactsRoute
  '/app/recovery-key': typeof AuthenticatedAppRecoveryKeyRoute
  '/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/app/shared': typeof AuthenticatedAppSharedRoute
  '/app/trash': typeof AuthenticatedAppTrashRoute
  '/setup/recovery-key': typeof AuthenticatedSetupRecoveryKeyRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/affiliates': typeof AuthenticatedAppAdminAffiliatesRoute
  '/app/f/$folderId': typeof AuthenticatedAppFFolderIdRoute
  '/app/admin': typeof AuthenticatedAppAdminIndexRoute
  '/app/admin/reports/$reportId': typeof AuthenticatedAppAdminReportsReportIdRoute
  '/app/admin/reports': typeof AuthenticatedAppAdminReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/account-deleted': typeof AccountDeletedRouteRoute
  '/login': typeof LoginRouteRoute
  '/pricing': typeof PricingRouteRoute
  '/privacy': typeof PrivacyRouteRoute
  '/recover': typeof RecoverRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/security': typeof SecurityRouteRoute
  '/terms': typeof TermsRouteRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/design.md': typeof DesignDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og.jpg': typeof OgDotjpgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/og/$key': typeof OgKeyRoute
  '/r/$code': typeof RCodeRoute
  '/recover/check-email': typeof RecoverCheckEmailRoute
  '/recover/complete': typeof RecoverCompleteRoute
  '/register/check-email': typeof RegisterCheckEmailRoute
  '/register/complete': typeof RegisterCompleteRoute
  '/s/$token': typeof STokenRoute
  '/vs/$slug': typeof VsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/recover/': typeof RecoverIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/_authenticated/app/account': typeof AuthenticatedAppAccountRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/contacts': typeof AuthenticatedAppContactsRoute
  '/_authenticated/app/recovery-key': typeof AuthenticatedAppRecoveryKeyRoute
  '/_authenticated/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/_authenticated/app/shared': typeof AuthenticatedAppSharedRoute
  '/_authenticated/app/trash': typeof AuthenticatedAppTrashRoute
  '/_authenticated/setup/recovery-key': typeof AuthenticatedSetupRecoveryKeyRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/affiliates': typeof AuthenticatedAppAdminAffiliatesRoute
  '/_authenticated/app/f/$folderId': typeof AuthenticatedAppFFolderIdRoute
  '/_authenticated/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/_authenticated/app/admin/reports/$reportId': typeof AuthenticatedAppAdminReportsReportIdRoute
  '/_authenticated/app/admin/reports/': typeof AuthenticatedAppAdminReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account-deleted'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/recover'
    | '/register'
    | '/security'
    | '/terms'
    | '/design.md'
    | '/llms.txt'
    | '/og.jpg'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/app'
    | '/api/$'
    | '/blog/$slug'
    | '/go/$slug'
    | '/og/$key'
    | '/r/$code'
    | '/recover/check-email'
    | '/recover/complete'
    | '/register/check-email'
    | '/register/complete'
    | '/s/$token'
    | '/vs/$slug'
    | '/blog/'
    | '/recover/'
    | '/register/'
    | '/app/account'
    | '/app/billing'
    | '/app/contacts'
    | '/app/recovery-key'
    | '/app/referrals'
    | '/app/shared'
    | '/app/trash'
    | '/setup/recovery-key'
    | '/app/'
    | '/app/admin/affiliates'
    | '/app/f/$folderId'
    | '/app/admin/'
    | '/app/admin/reports/$reportId'
    | '/app/admin/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account-deleted'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/design.md'
    | '/llms.txt'
    | '/og.jpg'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/$'
    | '/blog/$slug'
    | '/go/$slug'
    | '/og/$key'
    | '/r/$code'
    | '/recover/check-email'
    | '/recover/complete'
    | '/register/check-email'
    | '/register/complete'
    | '/s/$token'
    | '/vs/$slug'
    | '/blog'
    | '/recover'
    | '/register'
    | '/app/account'
    | '/app/billing'
    | '/app/contacts'
    | '/app/recovery-key'
    | '/app/referrals'
    | '/app/shared'
    | '/app/trash'
    | '/setup/recovery-key'
    | '/app'
    | '/app/admin/affiliates'
    | '/app/f/$folderId'
    | '/app/admin'
    | '/app/admin/reports/$reportId'
    | '/app/admin/reports'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account-deleted'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/recover'
    | '/register'
    | '/security'
    | '/terms'
    | '/_authenticated'
    | '/design.md'
    | '/llms.txt'
    | '/og.jpg'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/api/$'
    | '/blog/$slug'
    | '/go/$slug'
    | '/og/$key'
    | '/r/$code'
    | '/recover/check-email'
    | '/recover/complete'
    | '/register/check-email'
    | '/register/complete'
    | '/s/$token'
    | '/vs/$slug'
    | '/blog/'
    | '/recover/'
    | '/register/'
    | '/_authenticated/app/account'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/contacts'
    | '/_authenticated/app/recovery-key'
    | '/_authenticated/app/referrals'
    | '/_authenticated/app/shared'
    | '/_authenticated/app/trash'
    | '/_authenticated/setup/recovery-key'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/affiliates'
    | '/_authenticated/app/f/$folderId'
    | '/_authenticated/app/admin/'
    | '/_authenticated/app/admin/reports/$reportId'
    | '/_authenticated/app/admin/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRouteRoute: typeof AboutRouteRoute
  AccountDeletedRouteRoute: typeof AccountDeletedRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  PricingRouteRoute: typeof PricingRouteRoute
  PrivacyRouteRoute: typeof PrivacyRouteRoute
  RecoverRouteRoute: typeof RecoverRouteRouteWithChildren
  RegisterRouteRoute: typeof RegisterRouteRouteWithChildren
  SecurityRouteRoute: typeof SecurityRouteRoute
  TermsRouteRoute: typeof TermsRouteRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DesignDotmdRoute: typeof DesignDotmdRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OgDotjpgRoute: typeof OgDotjpgRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSplatRoute: typeof ApiSplatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GoSlugRoute: typeof GoSlugRoute
  OgKeyRoute: typeof OgKeyRoute
  RCodeRoute: typeof RCodeRoute
  STokenRoute: typeof STokenRoute
  VsSlugRoute: typeof VsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deleted': {
      id: '/account-deleted'
      path: '/account-deleted'
      fullPath: '/account-deleted'
      preLoaderRoute: typeof AccountDeletedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design.md': {
      id: '/design.md'
      path: '/design.md'
      fullPath: '/design.md'
      preLoaderRoute: typeof DesignDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og.jpg': {
      id: '/og.jpg'
      path: '/og.jpg'
      fullPath: '/og.jpg'
      preLoaderRoute: typeof OgDotjpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$slug': {
      id: '/go/$slug'
      path: '/go/$slug'
      fullPath: '/go/$slug'
      preLoaderRoute: typeof GoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$key': {
      id: '/og/$key'
      path: '/og/$key'
      fullPath: '/og/$key'
      preLoaderRoute: typeof OgKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover/': {
      id: '/recover/'
      path: '/'
      fullPath: '/recover/'
      preLoaderRoute: typeof RecoverIndexRouteImport
      parentRoute: typeof RecoverRouteRoute
    }
    '/recover/check-email': {
      id: '/recover/check-email'
      path: '/check-email'
      fullPath: '/recover/check-email'
      preLoaderRoute: typeof RecoverCheckEmailRouteImport
      parentRoute: typeof RecoverRouteRoute
    }
    '/recover/complete': {
      id: '/recover/complete'
      path: '/complete'
      fullPath: '/recover/complete'
      preLoaderRoute: typeof RecoverCompleteRouteImport
      parentRoute: typeof RecoverRouteRoute
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/register/check-email': {
      id: '/register/check-email'
      path: '/check-email'
      fullPath: '/register/check-email'
      preLoaderRoute: typeof RegisterCheckEmailRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/register/complete': {
      id: '/register/complete'
      path: '/complete'
      fullPath: '/register/complete'
      preLoaderRoute: typeof RegisterCompleteRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/$slug': {
      id: '/vs/$slug'
      path: '/vs/$slug'
      fullPath: '/vs/$slug'
      preLoaderRoute: typeof VsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/account': {
      id: '/_authenticated/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/contacts': {
      id: '/_authenticated/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AuthenticatedAppContactsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/recovery-key': {
      id: '/_authenticated/app/recovery-key'
      path: '/recovery-key'
      fullPath: '/app/recovery-key'
      preLoaderRoute: typeof AuthenticatedAppRecoveryKeyRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/referrals': {
      id: '/_authenticated/app/referrals'
      path: '/referrals'
      fullPath: '/app/referrals'
      preLoaderRoute: typeof AuthenticatedAppReferralsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/shared': {
      id: '/_authenticated/app/shared'
      path: '/shared'
      fullPath: '/app/shared'
      preLoaderRoute: typeof AuthenticatedAppSharedRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/trash': {
      id: '/_authenticated/app/trash'
      path: '/trash'
      fullPath: '/app/trash'
      preLoaderRoute: typeof AuthenticatedAppTrashRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/setup/recovery-key': {
      id: '/_authenticated/setup/recovery-key'
      path: '/setup/recovery-key'
      fullPath: '/setup/recovery-key'
      preLoaderRoute: typeof AuthenticatedSetupRecoveryKeyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin/': {
      id: '/_authenticated/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AuthenticatedAppAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/admin/affiliates': {
      id: '/_authenticated/app/admin/affiliates'
      path: '/admin/affiliates'
      fullPath: '/app/admin/affiliates'
      preLoaderRoute: typeof AuthenticatedAppAdminAffiliatesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/f/$folderId': {
      id: '/_authenticated/app/f/$folderId'
      path: '/f/$folderId'
      fullPath: '/app/f/$folderId'
      preLoaderRoute: typeof AuthenticatedAppFFolderIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/admin/reports/': {
      id: '/_authenticated/app/admin/reports/'
      path: '/admin/reports'
      fullPath: '/app/admin/reports/'
      preLoaderRoute: typeof AuthenticatedAppAdminReportsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/admin/reports/$reportId': {
      id: '/_authenticated/app/admin/reports/$reportId'
      path: '/admin/reports/$reportId'
      fullPath: '/app/admin/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedAppAdminReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface RecoverRouteRouteChildren {
  RecoverCheckEmailRoute: typeof RecoverCheckEmailRoute
  RecoverCompleteRoute: typeof RecoverCompleteRoute
  RecoverIndexRoute: typeof RecoverIndexRoute
}

const RecoverRouteRouteChildren: RecoverRouteRouteChildren = {
  RecoverCheckEmailRoute: RecoverCheckEmailRoute,
  RecoverCompleteRoute: RecoverCompleteRoute,
  RecoverIndexRoute: RecoverIndexRoute,
}

const RecoverRouteRouteWithChildren = RecoverRouteRoute._addFileChildren(
  RecoverRouteRouteChildren,
)

interface RegisterRouteRouteChildren {
  RegisterCheckEmailRoute: typeof RegisterCheckEmailRoute
  RegisterCompleteRoute: typeof RegisterCompleteRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteRouteChildren: RegisterRouteRouteChildren = {
  RegisterCheckEmailRoute: RegisterCheckEmailRoute,
  RegisterCompleteRoute: RegisterCompleteRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteRouteWithChildren = RegisterRouteRoute._addFileChildren(
  RegisterRouteRouteChildren,
)

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppContactsRoute: typeof AuthenticatedAppContactsRoute
  AuthenticatedAppRecoveryKeyRoute: typeof AuthenticatedAppRecoveryKeyRoute
  AuthenticatedAppReferralsRoute: typeof AuthenticatedAppReferralsRoute
  AuthenticatedAppSharedRoute: typeof AuthenticatedAppSharedRoute
  AuthenticatedAppTrashRoute: typeof AuthenticatedAppTrashRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAdminAffiliatesRoute: typeof AuthenticatedAppAdminAffiliatesRoute
  AuthenticatedAppFFolderIdRoute: typeof AuthenticatedAppFFolderIdRoute
  AuthenticatedAppAdminIndexRoute: typeof AuthenticatedAppAdminIndexRoute
  AuthenticatedAppAdminReportsReportIdRoute: typeof AuthenticatedAppAdminReportsReportIdRoute
  AuthenticatedAppAdminReportsIndexRoute: typeof AuthenticatedAppAdminReportsIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppContactsRoute: AuthenticatedAppContactsRoute,
  AuthenticatedAppRecoveryKeyRoute: AuthenticatedAppRecoveryKeyRoute,
  AuthenticatedAppReferralsRoute: AuthenticatedAppReferralsRoute,
  AuthenticatedAppSharedRoute: AuthenticatedAppSharedRoute,
  AuthenticatedAppTrashRoute: AuthenticatedAppTrashRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAdminAffiliatesRoute: AuthenticatedAppAdminAffiliatesRoute,
  AuthenticatedAppFFolderIdRoute: AuthenticatedAppFFolderIdRoute,
  AuthenticatedAppAdminIndexRoute: AuthenticatedAppAdminIndexRoute,
  AuthenticatedAppAdminReportsReportIdRoute:
    AuthenticatedAppAdminReportsReportIdRoute,
  AuthenticatedAppAdminReportsIndexRoute:
    AuthenticatedAppAdminReportsIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedSetupRecoveryKeyRoute: typeof AuthenticatedSetupRecoveryKeyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedSetupRecoveryKeyRoute: AuthenticatedSetupRecoveryKeyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRouteRoute: AboutRouteRoute,
  AccountDeletedRouteRoute: AccountDeletedRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  PricingRouteRoute: PricingRouteRoute,
  PrivacyRouteRoute: PrivacyRouteRoute,
  RecoverRouteRoute: RecoverRouteRouteWithChildren,
  RegisterRouteRoute: RegisterRouteRouteWithChildren,
  SecurityRouteRoute: SecurityRouteRoute,
  TermsRouteRoute: TermsRouteRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DesignDotmdRoute: DesignDotmdRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OgDotjpgRoute: OgDotjpgRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSplatRoute: ApiSplatRoute,
  BlogSlugRoute: BlogSlugRoute,
  GoSlugRoute: GoSlugRoute,
  OgKeyRoute: OgKeyRoute,
  RCodeRoute: RCodeRoute,
  STokenRoute: STokenRoute,
  VsSlugRoute: VsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
