import java.net.URI
import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
}

/*
 * The server a build type talks to, and the links it answers: one origin, so the app never
 * calls its own server's links "another server". -PdefaultOrigin=https://drive.example.org
 * points a self-hosted build at its own server; only https links are verified, through
 * that server's /.well-known/assetlinks.json.
 */
fun serves(type: com.android.build.api.dsl.ApplicationBuildType, fallback: String) {
    val origin = ((project.findProperty("defaultOrigin") as String?) ?: fallback).trimEnd('/')
    val uri = URI(origin)
    type.buildConfigField("String", "DEFAULT_ORIGIN", "\"$origin\"")
    type.manifestPlaceholders["appLinkScheme"] = uri.scheme
    type.manifestPlaceholders["appLinkHost"] = uri.host
    type.manifestPlaceholders["appLinkVerify"] = (uri.scheme == "https").toString()
}

/*
 * The upload key that signs what goes to Google Play, from apps/android/keystore.properties
 * (never committed) or the HUSHOS_UPLOAD_* environment variables; docs/release/signing.md has
 * the steps. Without a keystore and its password, release builds stay signed with the debug key
 * so a shrunk build still installs on a phone for testing; Play refuses a debug-signed bundle,
 * and scripts/bundle-release.sh refuses to produce one.
 */
val uploadKey: Map<String, String>? = run {
    val file = rootProject.file("keystore.properties")
    val properties = Properties()
    if (file.isFile) file.inputStream().use { properties.load(it) }
    fun value(key: String, variable: String): String? =
        properties.getProperty(key) ?: providers.environmentVariable(variable).orNull
    val storeFile = value("storeFile", "HUSHOS_UPLOAD_STORE_FILE") ?: return@run null
    // No password (a debug build, say): stay on the debug key rather than fail every task.
    val storePassword = value("storePassword", "HUSHOS_UPLOAD_STORE_PASSWORD") ?: return@run null
    mapOf(
        "storeFile" to storeFile,
        "storePassword" to storePassword,
        "keyAlias" to (value("keyAlias", "HUSHOS_UPLOAD_KEY_ALIAS") ?: "upload"),
        "keyPassword" to (value("keyPassword", "HUSHOS_UPLOAD_KEY_PASSWORD") ?: storePassword),
    )
}

android {
    namespace = "com.hushos.app"
    compileSdk = 37

    defaultConfig {
        applicationId = "com.hushos.app"
        minSdk = 29
        targetSdk = 36
        versionCode = 1
        versionName = "0.1.0"
    }

    signingConfigs {
        if (uploadKey != null) {
            create("upload") {
                storeFile = rootProject.file(uploadKey.getValue("storeFile"))
                storePassword = uploadKey.getValue("storePassword")
                keyAlias = uploadKey.getValue("keyAlias")
                keyPassword = uploadKey.getValue("keyPassword")
            }
        }
    }

    buildTypes {
        // Debug talks to the dev server (`adb reverse tcp:5173 tcp:5173` makes localhost reach it,
        // on the emulator and on a phone over USB); release talks to production.
        debug { serves(this, "http://localhost:5173") }
        release {
            serves(this, "https://hushos.com")
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            signingConfig = signingConfigs.getByName(if (uploadKey != null) "upload" else "debug")
        }
    }

    // JNA ships x86 and mips loaders too; phones and the emulator are arm64 and x86_64.
    packaging {
        jniLibs.excludes += listOf("**/x86/**", "**/mips/**", "**/mips64/**", "**/armeabi/**", "**/armeabi-v7a/**")
        resources.excludes += "/META-INF/{AL2.0,LGPL2.1}"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    // The Alpine tokens (com.hushos.tokens), generated by `bun run tokens` from packages/tokens.
    // Read in place, not copied, so regenerating them updates the app.
    sourceSets.getByName("main").kotlin.srcDir("../../../packages/tokens/generated")
}

dependencies {
    implementation(project(":core"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.navigation.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.foundation)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons)
    implementation(libs.androidx.security.crypto)
    implementation(libs.androidx.documentfile)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.coil.compose)
    implementation(libs.androidx.work.runtime)
    // QR codes for links (encoding only): the same address as Copy link, drawn for a camera.
    implementation(libs.zxing.core)
    // Scanning a recovery kit's code: CameraX frames, decoded by ZXing on the phone.
    // Privacy policy and terms open in a Custom Tab.
    implementation(libs.androidx.browser)
    implementation(libs.androidx.camera.camera2)
    implementation(libs.androidx.camera.lifecycle)
    implementation(libs.androidx.camera.view)
    testImplementation(libs.junit)
    // JVM tests open real envelopes: JNA's desktop jar loads the core built for this machine.
    testImplementation(libs.jna)
}

/*
 * The Rust core for this machine, for JVM unit tests that seal and open real envelopes
 * (restored-version sizes, for one). Built by cargo next to the phone libraries.
 */
val repoRoot: File = rootProject.projectDir.parentFile.parentFile
val hostCore = tasks.register<Exec>("hostCore") {
    workingDir = repoRoot
    commandLine("cargo", "build", "-q", "-p", "hushos-core", "--release")
}
tasks.withType<Test>().configureEach {
    dependsOn(hostCore)
    systemProperty("jna.library.path", File(repoRoot, "target/release").path)
}
