/*
 * Writes the Alpine tokens out for each client. The outputs are checked in so the
 * native apps build without Bun; run `bun run tokens` after changing src/index.ts.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { color, font, radius, shadow, space, type, type Scheme } from '../src/index';

const out = join(import.meta.dir, '..', 'generated');
mkdirSync(out, { recursive: true });

const header =
    'Generated by packages/tokens/scripts/generate.ts. Edit packages/tokens/src/index.ts instead.';
const roles = Object.entries(color);
const kebab = (name: string) => name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const pascal = (name: string) => name[0]!.toUpperCase() + name.slice(1);

const elevations = Object.entries(shadow);

function cssBlock(scheme: Scheme) {
    return [
        ...roles.map(([name, role]) => `    --${kebab(name)}: ${role[scheme]};`),
        ...elevations.map(([name, role]) => `    --elevation-${name}: ${role[scheme]};`),
    ].join('\n');
}

const indent = (block: string) =>
    block.replaceAll('\n    ', '\n        ').replace(/^ {4}/, '        ');

const css = `/* ${header} */

/*
 * Light by default; dark follows the system unless an ancestor has .light, and
 * .dark forces it for a subtree (the design board shows both side by side).
 * High contrast follows prefers-contrast: more, and .hc forces it.
 */
:root,
.light {
${cssBlock('light')}
    color-scheme: light;
}

@media (prefers-color-scheme: dark) {
    :root:not(.light) {
${indent(cssBlock('dark'))}
        color-scheme: dark;
    }
}

.dark {
${cssBlock('dark')}
    color-scheme: dark;
}

@media (prefers-contrast: more) {
    :root:not(.dark) {
${indent(cssBlock('lightHigh'))}
    }
}

@media (prefers-contrast: more) and (prefers-color-scheme: dark) {
    :root:not(.light) {
${indent(cssBlock('darkHigh'))}
    }
}

.hc:not(.dark) {
${cssBlock('lightHigh')}
}

/* Forced high contrast with the scheme left to the system: dark when the system is. */
@media (prefers-color-scheme: dark) {
    .hc:not(.light) {
${indent(cssBlock('darkHigh'))}
    }
}

.dark.hc {
${cssBlock('darkHigh')}
}

@theme inline {
${roles.map(([name]) => `    --color-${kebab(name)}: var(--${kebab(name)});`).join('\n')}
${elevations.map(([name]) => `    --shadow-${name}: var(--elevation-${name});`).join('\n')}
    --font-brand: '${font.brand} Variable', '${font.brand}', ui-sans-serif, system-ui, sans-serif;
    --font-mono: '${font.mono} Variable', '${font.mono}', ui-monospace, Menlo, monospace;
${Object.entries(radius)
    .map(([name, value]) => `    --radius-${name}: ${value}px;`)
    .join('\n')}
}
`;

/** #RRGGBB or #RRGGBBAA as an ARGB integer literal body. */
function argb(hex: string) {
    const value = hex.slice(1).toUpperCase();
    const rgb = value.slice(0, 6);
    const alpha = value.length === 8 ? value.slice(6) : 'FF';
    return `${alpha}${rgb}`;
}

const swift = `// ${header}

import SwiftUI
import UIKit

/// Alpine colours. Each resolves to light, dark or their high-contrast twins from the trait collection.
public enum Alpine {
${roles
    .map(
        ([name, role]) =>
            `    /// ${role.use}\n    public static let ${name} = Color(alpineLight: 0x${argb(role.light)}, dark: 0x${argb(role.dark)}, lightHigh: 0x${argb(role.lightHigh)}, darkHigh: 0x${argb(role.darkHigh)})`,
    )
    .join('\n')}

    public enum Radius {
${Object.entries(radius)
    .map(([name, value]) => `        public static let ${name}: CGFloat = ${value}`)
    .join('\n')}
    }

    public enum Space {
${Object.entries(space)
    .map(([name, value]) => `        public static let s${name}: CGFloat = ${value}`)
    .join('\n')}
    }

    /// The brand face for large titles and onboarding headlines; everything else uses the system font.
    public static func brand(_ size: CGFloat, weight: Font.Weight = .heavy) -> Font {
        .custom("${font.brand}", size: size, relativeTo: .largeTitle).weight(weight)
    }
}

extension Color {
    init(alpineLight light: UInt32, dark: UInt32, lightHigh: UInt32, darkHigh: UInt32) {
        self.init(uiColor: UIColor { traits in
            let high = traits.accessibilityContrast == .high
            let value = traits.userInterfaceStyle == .dark ? (high ? darkHigh : dark) : (high ? lightHigh : light)
            return UIColor(
                red: CGFloat((value >> 16) & 0xFF) / 255,
                green: CGFloat((value >> 8) & 0xFF) / 255,
                blue: CGFloat(value & 0xFF) / 255,
                alpha: CGFloat((value >> 24) & 0xFF) / 255
            )
        })
    }
}
`;

function kotlinScheme(scheme: Scheme) {
    return roles
        .map(([name, role]) => `    val ${pascal(name)} = Color(0x${argb(role[scheme])})`)
        .join('\n');
}

const kotlin = `// ${header}

package com.hushos.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object AlpineLight {
${kotlinScheme('light')}
}

object AlpineDark {
${kotlinScheme('dark')}
}

/** High contrast, for UiModeManager.contrast at or above 0.5 (Android 14+). */
object AlpineLightHigh {
${kotlinScheme('lightHigh')}
}

object AlpineDarkHigh {
${kotlinScheme('darkHigh')}
}

object AlpineRadius {
${Object.entries(radius)
    .map(([name, value]) => `    val ${pascal(name)} = ${value}.dp`)
    .join('\n')}
}

object AlpineSpace {
${Object.entries(space)
    .map(([name, value]) => `    val S${name} = ${value}.dp`)
    .join('\n')}
}

object AlpineType {
${Object.entries(type)
    .map(([name, value]) => `    val ${pascal(name)} = ${value.size}.sp`)
    .join('\n')}
}
`;

writeFileSync(join(out, 'tokens.css'), css);
writeFileSync(join(out, 'Alpine.swift'), swift);
writeFileSync(join(out, 'Alpine.kt'), kotlin);
console.log(`Wrote ${roles.length} colour roles to ${out}`);
