#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
    BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
    BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
    BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
    [[ -t 1 ]] || return 0
    if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
    _clear
    printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
    printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
    printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
    printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
    printf '  later, since it remembers values already saved.%s\n' "$RESET"
    pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
    _clear
    _STAGE_INDEX=$((_STAGE_INDEX + 1))
    printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
        "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
    local url="$1"
    printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
    { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
        elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
        elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
        elif command -v open        >/dev/null 2>&1; then open "$url"
        else warn "couldn't open a browser; visit it manually: $url"; fi
    } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
    printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
    read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
    local reply=""
    printf '  %s? %s [y/N] ' "$YELLOW" "$1"
    read -r reply || true
    [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
    [[ -f "$ENV_FILE" ]] || return 1
    local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
    printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
    local key="$1" prompt="$2" current input
    current=$(_existing "$key" || true)
    if [[ -n "$current" ]]; then
        printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
        printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    read -r input || true
    [[ -z "$input" && -n "$current" ]] && input="$current"
    printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
    local key="$1" prompt="$2" current input
    current=$(_existing "$key" || true)
    if [[ -n "$current" ]]; then
        printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
        printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    read -rs input || true
    printf '\n'
    [[ -z "$input" && -n "$current" ]] && input="$current"
    printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
    local key="$1" value="$2" tmp
    touch "$ENV_FILE"
    tmp=$(mktemp)
    grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
    printf '%s=%s\n' "$key" "$value" >> "$tmp"
    mv "$tmp" "$ENV_FILE"
    WRITTEN_ENV+=("$key")
    printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
    local name="$1" value="$2"
    if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
        if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
            WRITTEN_SECRET+=("$name")
            printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
            return
        fi
    fi
    SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
    warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
    local name="$1" value="$2"
    if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
        if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
            printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
            return
        fi
    fi
    SKIPPED+=("GitHub variable $name")
    warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
    _clear
    printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
    (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
    (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
    if (( ${#SKIPPED[@]} )); then
        printf '\n'; warn "still to do by hand:"
        for s in "${SKIPPED[@]}"; do note "  - $s"; done
    fi
    printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# HushOS store release: the steps only the owner can take (accounts, keys, portal pages),
# in the order of docs/release/README.md, with checks where a machine can check. Values that
# are not secret (D-U-N-S, Team ID, certificate fingerprints) go to .env.release, which git
# ignores; passwords go to the macOS keychain and are never printed. Re-run it any time: each
# stage shows what is already done. Run from the repository root: scripts/release-wizard.sh
# The builds it offers use RELEASE_VERSION (default 1.0.0) and RELEASE_BUILD (default 1).

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"
ENV_FILE="$ROOT/.env.release"
SITE="https://hushos.com"
KEYCHAIN_ITEM="hushos-android-upload"
export JAVA_HOME="${JAVA_HOME:-/opt/homebrew/opt/openjdk@21}"
KEYTOOL="$JAVA_HOME/bin/keytool"
ok() { printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }
bad() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }
# The JSON a .well-known URL serves, or nothing when it is missing or not JSON.
well_known() { curl -fsS --max-time 15 -H 'Accept: application/json' "$1" 2>/dev/null | grep -E '^[[:space:]]*[[{]' || true; }

TOTAL_STAGES=12

banner "HushOS: App Store and Google Play release"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "D-U-N-S number for HushOS, Inc."
say "Both stores verify an organization against its Dun & Bradstreet record."
say "You applied already; D&B takes up to 5 business days (Apple's figure; Google says up to 30)."
ask DUNS_NUMBER "D-U-N-S number, 9 digits (Enter to skip if it hasn't arrived):"
if [[ "$DUNS_NUMBER" =~ ^[0-9]{9}$ ]]; then
    write_env DUNS_NUMBER "$DUNS_NUMBER"
    say "Check that Apple sees it under the exact legal name, HushOS, Inc.:"
    open_url "https://developer.apple.com/enroll/duns-lookup/"
    step "Sign in, fill in HushOS, Inc. and its address exactly as on the D&B record, submit."
    step "Apple should return the same number. If it can't find it, wait 2 business days after D&B issues it."
    pause "Press Enter when Apple's lookup shows the number (or to come back to it later)"
else
    warn "Not yet. Stages 2, 7 and 11 can go ahead now; Apple (3-6) and Google (8-10) wait for it."
    SKIPPED+=("D-U-N-S number: re-run this wizard when D&B issues it")
    pause
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Apple Account with two-factor authentication"
say "Enroll with an Apple Account on a hushos.com address that you, as an officer"
say "of HushOS, Inc., control (Apple wants a work email on the organization's domain)."
if dig +short MX hushos.com | grep -q .; then ok "hushos.com receives email (MX records exist)"; else bad "hushos.com has no MX records"; fi
open_url "https://account.apple.com"
step "Sign in (or create the account), then Sign-In and Security > Two-Factor Authentication: On."
step "Add a trusted phone number you will keep."
pause "Press Enter when two-factor authentication is on"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Apple Developer Program, as an organization"
if [[ -z "$(_existing DUNS_NUMBER || true)" ]]; then
    warn "Needs the D-U-N-S number. Skip for now and re-run later."
    SKIPPED+=("Apple Developer Program enrollment (after the D-U-N-S number)")
    pause
else
    open_url "https://developer.apple.com/programs/enroll/"
    step "Start Your Enrollment > sign in > entity type: Company / Organization."
    step "Legal entity name: HushOS, Inc. (no DBA). D-U-N-S: the number above. Website: $SITE"
    step "You must have authority to bind HushOS, Inc.; Apple may phone to confirm. Pay the 99 USD fee."
    note "docs/release/apple.md, section 1, has every field."
    pause "Press Enter once Apple confirms the membership (an email; can take days)"
    open_url "https://developer.apple.com/account#MembershipDetailsCard"
    step "Membership details > Team ID: 10 capital letters and digits."
    ask APPLE_TEAM_ID "Team ID:"
    if [[ "$APPLE_TEAM_ID" =~ ^[A-Z0-9]{10}$ ]]; then write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"; else bad "That isn't a Team ID; re-run this stage later."; fi
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Xcode signed in to the team"
if [[ -z "$(_existing APPLE_TEAM_ID || true)" ]]; then
    warn "Needs the Team ID (stage 3)."
    SKIPPED+=("Xcode account and first archive (after enrollment)")
    pause
else
    step "Xcode > Settings > Accounts > + > Apple Account: sign in with the enrolled account."
    step "Select HushOS, Inc. in the list: your role should be Account Holder or Admin."
    say "Signing is automatic: the first archive registers the five bundle IDs, the app group"
    say "group.com.hushos.app and the Associated Domains capability (docs/release/signing.md)."
    pause "Press Enter when Xcode shows the team"
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Universal links: APPLE_APP_IDS on the production server"
TEAM=$(_existing APPLE_TEAM_ID || true)
if [[ -z "$TEAM" ]]; then
    warn "Needs the Team ID (stage 3)."
    SKIPPED+=("APPLE_APP_IDS on production")
    pause
else
    say "On the production server's environment (docs/self-hosting.md), set:"
    printf '\n      %sAPPLE_APP_IDS=%s.com.hushos.app%s\n\n' "$BOLD" "$TEAM" "$RESET"
    say "then restart the web service."
    pause "Press Enter when it is deployed"
    if well_known "$SITE/.well-known/apple-app-site-association" | grep -q "$TEAM.com.hushos.app"; then
        ok "$SITE/.well-known/apple-app-site-association names $TEAM.com.hushos.app"
    else
        bad "$SITE/.well-known/apple-app-site-association doesn't name $TEAM.com.hushos.app yet"
        SKIPPED+=("AASA on $SITE")
    fi
    note "Apple's CDN fetches it within 24 hours; check later at"
    note "https://app-site-association.cdn-apple.com/a/v1/hushos.com"
    pause
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "App Store Connect: the app record and first TestFlight build"
if [[ -z "$TEAM" ]]; then
    warn "Needs the Team ID (stage 3)."
    SKIPPED+=("App Store Connect app record and first build")
    pause
else
    open_url "https://appstoreconnect.apple.com/business"
    step "Business: accept the latest Program License Agreement (the Account Holder must)."
    open_url "https://appstoreconnect.apple.com/apps"
    step "Apps > + > New App. Platform iOS, name HushOS, language English (U.S.),"
    step "bundle ID com.hushos.app, SKU hushos-ios, user access Full."
    note "If the bundle ID isn't in the list yet, the next step's archive registers it; come back."
    if confirm "Archive and upload version ${RELEASE_VERSION:-1.0.0}, build ${RELEASE_BUILD:-1} now?"; then
        DEVELOPMENT_TEAM="$TEAM" apps/ios/scripts/archive.sh "${RELEASE_VERSION:-1.0.0}" "${RELEASE_BUILD:-1}" || bad "The archive failed; see the output above and docs/release/apple.md."
    fi
    pause "Press Enter to continue"
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Android upload key"
KEYSTORE=$(_existing ANDROID_UPLOAD_KEYSTORE || true)
KEYSTORE="${KEYSTORE:-$HOME/.hushos/hushos-upload.jks}"
if [[ -f "$KEYSTORE" ]]; then
    ok "The upload keystore exists at $KEYSTORE"
else
    say "The upload key signs every bundle you send to Google Play. It lives outside the"
    say "repository, at $KEYSTORE, and its password lives in your login keychain."
    say "Pick a long password and store it in your password manager too."
    if confirm "Create the upload key now?"; then
        mkdir -p "$(dirname "$KEYSTORE")"
        chmod 700 "$(dirname "$KEYSTORE")"
        security delete-generic-password -s "$KEYCHAIN_ITEM" -a upload >/dev/null 2>&1 || true
        say "The keychain asks for the password twice:"
        security add-generic-password -s "$KEYCHAIN_ITEM" -a upload -l "HushOS Android upload key" -w
        HUSHOS_UPLOAD_STORE_PASSWORD=$(security find-generic-password -s "$KEYCHAIN_ITEM" -a upload -w)
        export HUSHOS_UPLOAD_STORE_PASSWORD
        "$KEYTOOL" -genkeypair -keystore "$KEYSTORE" -storetype PKCS12 -alias upload \
            -keyalg RSA -keysize 4096 -validity 10000 \
            -dname "CN=HushOS, O=HushOS Inc., C=US" \
            -storepass:env HUSHOS_UPLOAD_STORE_PASSWORD
        unset HUSHOS_UPLOAD_STORE_PASSWORD
        chmod 600 "$KEYSTORE"
        ok "Created $KEYSTORE"
        warn "Back it up now: copy the .jks file and the password to your password manager."
    fi
fi
if [[ -f "$KEYSTORE" ]]; then
    write_env ANDROID_UPLOAD_KEYSTORE "$KEYSTORE"
    printf 'storeFile=%s\nkeyAlias=upload\n' "$KEYSTORE" > apps/android/keystore.properties
    ok "apps/android/keystore.properties points at it (no password in it; git ignores it)"
    if HUSHOS_UPLOAD_STORE_PASSWORD=$(security find-generic-password -s "$KEYCHAIN_ITEM" -a upload -w 2>/dev/null); then
        export HUSHOS_UPLOAD_STORE_PASSWORD
        UPLOAD_SHA=$("$KEYTOOL" -list -v -keystore "$KEYSTORE" -alias upload -storepass:env HUSHOS_UPLOAD_STORE_PASSWORD \
            2>/dev/null | awk '/SHA256:/ {print $2; exit}' || true)
        unset HUSHOS_UPLOAD_STORE_PASSWORD
        if [[ -n "$UPLOAD_SHA" ]]; then
            write_env ANDROID_UPLOAD_SHA256 "$UPLOAD_SHA"
        else
            bad "Couldn't read the keystore with the keychain's password: they don't match."
        fi
    else
        bad "The keychain has no $KEYCHAIN_ITEM item: builds will ask for HUSHOS_UPLOAD_STORE_PASSWORD."
    fi
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Google Play Console, as an organization"
if [[ -z "$(_existing DUNS_NUMBER || true)" ]]; then
    warn "Needs the D-U-N-S number. Meanwhile, create the Google account you'll use (a hushos.com address)."
    SKIPPED+=("Play Console organization account (after the D-U-N-S number)")
    pause
else
    open_url "https://play.google.com/console/signup"
    step "Choose 'An organization or business'. Organization: HushOS, Inc.; D-U-N-S: the number above."
    step "Developer email and phone are shown publicly on Play; the contact ones are private."
    step "Website $SITE: verify it in Search Console with the same Google account (next page opens it)."
    open_url "https://search.google.com/search-console"
    step "Pay the 25 USD fee; upload the identity and organization documents when asked."
    note "docs/release/google.md, section 1, has every field."
    pause "Press Enter once Google confirms the account (an email; can take days)"
fi

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "The first Android App Bundle"
if [[ ! -f apps/android/keystore.properties ]]; then
    warn "Needs the upload key (stage 7)."
    SKIPPED+=("First Android bundle")
elif confirm "Build version ${RELEASE_VERSION:-1.0.0}, version code ${RELEASE_BUILD:-1} now?"; then
    apps/android/scripts/bundle-release.sh "${RELEASE_VERSION:-1.0.0}" "${RELEASE_BUILD:-1}" || bad "The build failed; see the output above."
    say "Upload apps/android/app/build/outputs/bundle/release/app-release.aab to Internal testing"
    say "(docs/release/google.md, section 5). The first upload sets up Play App Signing."
fi
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "App links: ANDROID_APP_CERT_SHA256 on the production server"
UPLOAD_SHA=$(_existing ANDROID_UPLOAD_SHA256 || true)
say "After the first upload, Play signs the app with its own key. Find that key's fingerprint:"
step "Play Console > HushOS > Protected with Play > Play Store distribution > Go to Play"
step "app signing (older menus: Release > Setup > App signing),"
step "'App signing key certificate' > SHA-256 certificate fingerprint > copy."
ask ANDROID_APP_SIGNING_SHA256 "App signing key SHA-256 (Enter to skip until you've uploaded):"
if [[ "$ANDROID_APP_SIGNING_SHA256" =~ ^([0-9A-Fa-f]{2}:){31}[0-9A-Fa-f]{2}$ ]]; then
    write_env ANDROID_APP_SIGNING_SHA256 "$ANDROID_APP_SIGNING_SHA256"
    VALUE="$ANDROID_APP_SIGNING_SHA256${UPLOAD_SHA:+,$UPLOAD_SHA}"
    say "On the production server, set (the Play key first; the upload key keeps sideloaded"
    say "release builds working too):"
    printf '\n      %sANDROID_APP_CERT_SHA256=%s%s\n\n' "$BOLD" "$VALUE" "$RESET"
    pause "Press Enter when it is deployed"
    if well_known "$SITE/.well-known/assetlinks.json" | grep -qi "$ANDROID_APP_SIGNING_SHA256"; then
        ok "$SITE/.well-known/assetlinks.json lists the Play signing key"
    else
        bad "$SITE/.well-known/assetlinks.json doesn't list it yet"
        SKIPPED+=("assetlinks.json on $SITE")
    fi
else
    SKIPPED+=("Play app signing fingerprint and ANDROID_APP_CERT_SHA256")
fi
pause

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Public pages the stores link to"
for path in / /privacy /terms /security; do
    code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 "$SITE$path" || true)
    [[ "$code" == 200 ]] && ok "$SITE$path" || bad "$SITE$path answers $code"
done
ask SUPPORT_URL "Support URL with HushOS, Inc.'s address, email and phone (Apple requires all three):"
if [[ -n "$SUPPORT_URL" ]]; then
    write_env SUPPORT_URL "$SUPPORT_URL"
    code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 "$SUPPORT_URL" || true)
    [[ "$code" == 200 ]] && ok "$SUPPORT_URL" || bad "$SUPPORT_URL answers $code"
else
    SKIPPED+=("A support page with address, email and phone (docs/release/checklist.md)")
fi
ask SUPPORT_EMAIL "Support email shown on both stores (e.g. hello@hushos.com):"
if [[ -n "$SUPPORT_EMAIL" ]]; then
    write_env SUPPORT_EMAIL "$SUPPORT_EMAIL"
    step "Send a test message to $SUPPORT_EMAIL from another account and check it arrives."
    pause "Press Enter once it arrived"
fi

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Before you press Submit"
say "Work through docs/release/checklist.md. The ones only a phone can check:"
step "Install the TestFlight build and the internal-test build on real phones."
step "Tap a share link from Mail or Messages (https://hushos.com/s/...): it must open in HushOS."
step "Sign in with the review demo account on both, then sign out."
pause "Press Enter to finish"

finish
