// swift-tools-version:6.0
import PackageDescription

/* The Rust core for Apple platforms. Generated by apps/ios/scripts/build-core.sh; the xcframework and Sources are not committed. */
let package = Package(
    name: "HushOSCore",
    platforms: [.iOS(.v18), .macOS(.v15)],
    products: [.library(name: "HushOSCore", targets: ["HushOSCore"])],
    targets: [
        .binaryTarget(name: "HushOSCoreFFI", path: "HushOSCoreFFI.xcframework"),
        .target(name: "HushOSCore", dependencies: ["HushOSCoreFFI"]),
    ]
)
